# Generated by Django 4.2.7 on 2023-11-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_annotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='document',
        ),
        migrations.RemoveField(
            model_name='label',
            name='color',
        ),
        migrations.AlterField(
            model_name='annotation',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
